# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: terraform-to-ansible

  # A short description of the repository that will show up on GitHub
  description: Terraform to Ansible - Consume Terraform State as Ansible Inventory
