---
image: python:3.7

before_script:
  - python --version
  - pip3 install pip-tools
  - pip-sync requirements.txt requirements-dev.txt

stages:
  - linting

black:
  stage: linting
  script:
    - black terraform_to_ansible/ --check

flake8:
  stage: linting
  script:
    - flake8 terraform_to_ansible/

pylint:
  stage: linting
  script:
    - pylint terraform_to_ansible/
