---
language: python

python:
  - 3.7

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install flake8 pylint

script:
  - flake8 terraform_to_ansible/
  - pylint terraform_to_ansible/
